export const DEFAULT_MAX_FILE_SIZE_MB = 100;
export const DEFAULT_UPLOAD_PRESIGN_TTL_HOURS = 24;
export const DEFAULT_DOWNLOAD_PRESIGN_TTL_MINUTES = 15;
export const MAX_UPLOAD_PRESIGN_TTL_HOURS = 48;
export const MAX_DOWNLOAD_PRESIGN_TTL_MINUTES = 60;
