/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpRouteRouteImport } from './routes/op/route'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as UnlinkedRouteImport } from './routes/unlinked'
import { Route as OpIndexRouteImport } from './routes/op/index'
import { Route as OpInvoicesRouteImport } from './routes/op/invoices'
import { Route as OpSettingsRouteImport } from './routes/op/settings'
import { Route as WClientIdRouteRouteImport } from './routes/w/$clientId/route'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api.auth.sign-in'
import { Route as ApiAuthSignOutRouteImport } from './routes/api.auth.sign-out'
import { Route as OpClientsIndexRouteImport } from './routes/op/clients/index'
import { Route as OpClientsClientIdRouteRouteImport } from './routes/op/clients/$clientId/route'
import { Route as WClientIdIndexRouteImport } from './routes/w/$clientId/index'
import { Route as WClientIdFilesRouteImport } from './routes/w/$clientId/files'
import { Route as WClientIdInsightsRouteImport } from './routes/w/$clientId/insights'
import { Route as WClientIdInvoicesRouteImport } from './routes/w/$clientId/invoices'
import { Route as OpClientsClientIdIndexRouteImport } from './routes/op/clients/$clientId/index'
import { Route as OpClientsClientIdFilesRouteImport } from './routes/op/clients/$clientId/files'
import { Route as OpClientsClientIdInsightsRouteImport } from './routes/op/clients/$clientId/insights'
import { Route as OpClientsClientIdInvoicesRouteImport } from './routes/op/clients/$clientId/invoices'
import { Route as OpClientsClientIdSettingsRouteImport } from './routes/op/clients/$clientId/settings'
import { Route as WClientIdFilesIndexRouteImport } from './routes/w/$clientId/files/index'
import { Route as WClientIdFilesRequestIdRouteImport } from './routes/w/$clientId/files/$requestId'
import { Route as OpClientsClientIdFilesIndexRouteImport } from './routes/op/clients/$clientId/files/index'
import { Route as OpClientsClientIdFilesRequestIdRouteImport } from './routes/op/clients/$clientId/files/$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpRouteRoute = OpRouteRouteImport.update({
  id: '/op',
  path: '/op',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlinkedRoute = UnlinkedRouteImport.update({
  id: '/unlinked',
  path: '/unlinked',
  getParentRoute: () => rootRouteImport,
} as any)
const OpIndexRoute = OpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpRouteRoute,
} as any)
const OpInvoicesRoute = OpInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => OpRouteRoute,
} as any)
const OpSettingsRoute = OpSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OpRouteRoute,
} as any)
const WClientIdRouteRoute = WClientIdRouteRouteImport.update({
  id: '/w/$clientId',
  path: '/w/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const OpClientsIndexRoute = OpClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => OpRouteRoute,
} as any)
const OpClientsClientIdRouteRoute = OpClientsClientIdRouteRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => OpRouteRoute,
} as any)
const WClientIdIndexRoute = WClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WClientIdRouteRoute,
} as any)
const WClientIdFilesRoute = WClientIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => WClientIdRouteRoute,
} as any)
const WClientIdInsightsRoute = WClientIdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => WClientIdRouteRoute,
} as any)
const WClientIdInvoicesRoute = WClientIdInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => WClientIdRouteRoute,
} as any)
const OpClientsClientIdIndexRoute = OpClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpClientsClientIdRouteRoute,
} as any)
const OpClientsClientIdFilesRoute = OpClientsClientIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OpClientsClientIdRouteRoute,
} as any)
const OpClientsClientIdInsightsRoute =
  OpClientsClientIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => OpClientsClientIdRouteRoute,
  } as any)
const OpClientsClientIdInvoicesRoute =
  OpClientsClientIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => OpClientsClientIdRouteRoute,
  } as any)
const OpClientsClientIdSettingsRoute =
  OpClientsClientIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OpClientsClientIdRouteRoute,
  } as any)
const WClientIdFilesIndexRoute = WClientIdFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WClientIdFilesRoute,
} as any)
const WClientIdFilesRequestIdRoute = WClientIdFilesRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => WClientIdFilesRoute,
} as any)
const OpClientsClientIdFilesIndexRoute =
  OpClientsClientIdFilesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OpClientsClientIdFilesRoute,
  } as any)
const OpClientsClientIdFilesRequestIdRoute =
  OpClientsClientIdFilesRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => OpClientsClientIdFilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/op': typeof OpRouteRouteWithChildren
  '/signout': typeof SignoutRoute
  '/unlinked': typeof UnlinkedRoute
  '/w/$clientId': typeof WClientIdRouteRouteWithChildren
  '/op/invoices': typeof OpInvoicesRoute
  '/op/settings': typeof OpSettingsRoute
  '/op/': typeof OpIndexRoute
  '/op/clients/$clientId': typeof OpClientsClientIdRouteRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/w/$clientId/files': typeof WClientIdFilesRouteWithChildren
  '/w/$clientId/insights': typeof WClientIdInsightsRoute
  '/w/$clientId/invoices': typeof WClientIdInvoicesRoute
  '/op/clients/': typeof OpClientsIndexRoute
  '/w/$clientId/': typeof WClientIdIndexRoute
  '/op/clients/$clientId/files': typeof OpClientsClientIdFilesRouteWithChildren
  '/op/clients/$clientId/insights': typeof OpClientsClientIdInsightsRoute
  '/op/clients/$clientId/invoices': typeof OpClientsClientIdInvoicesRoute
  '/op/clients/$clientId/settings': typeof OpClientsClientIdSettingsRoute
  '/w/$clientId/files/$requestId': typeof WClientIdFilesRequestIdRoute
  '/op/clients/$clientId/': typeof OpClientsClientIdIndexRoute
  '/w/$clientId/files/': typeof WClientIdFilesIndexRoute
  '/op/clients/$clientId/files/$requestId': typeof OpClientsClientIdFilesRequestIdRoute
  '/op/clients/$clientId/files/': typeof OpClientsClientIdFilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signout': typeof SignoutRoute
  '/unlinked': typeof UnlinkedRoute
  '/op/invoices': typeof OpInvoicesRoute
  '/op/settings': typeof OpSettingsRoute
  '/op': typeof OpIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/w/$clientId/insights': typeof WClientIdInsightsRoute
  '/w/$clientId/invoices': typeof WClientIdInvoicesRoute
  '/op/clients': typeof OpClientsIndexRoute
  '/w/$clientId': typeof WClientIdIndexRoute
  '/op/clients/$clientId/insights': typeof OpClientsClientIdInsightsRoute
  '/op/clients/$clientId/invoices': typeof OpClientsClientIdInvoicesRoute
  '/op/clients/$clientId/settings': typeof OpClientsClientIdSettingsRoute
  '/w/$clientId/files/$requestId': typeof WClientIdFilesRequestIdRoute
  '/op/clients/$clientId': typeof OpClientsClientIdIndexRoute
  '/w/$clientId/files': typeof WClientIdFilesIndexRoute
  '/op/clients/$clientId/files/$requestId': typeof OpClientsClientIdFilesRequestIdRoute
  '/op/clients/$clientId/files': typeof OpClientsClientIdFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/op': typeof OpRouteRouteWithChildren
  '/signout': typeof SignoutRoute
  '/unlinked': typeof UnlinkedRoute
  '/w/$clientId': typeof WClientIdRouteRouteWithChildren
  '/op/invoices': typeof OpInvoicesRoute
  '/op/settings': typeof OpSettingsRoute
  '/op/': typeof OpIndexRoute
  '/op/clients/$clientId': typeof OpClientsClientIdRouteRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/w/$clientId/files': typeof WClientIdFilesRouteWithChildren
  '/w/$clientId/insights': typeof WClientIdInsightsRoute
  '/w/$clientId/invoices': typeof WClientIdInvoicesRoute
  '/op/clients/': typeof OpClientsIndexRoute
  '/w/$clientId/': typeof WClientIdIndexRoute
  '/op/clients/$clientId/files': typeof OpClientsClientIdFilesRouteWithChildren
  '/op/clients/$clientId/insights': typeof OpClientsClientIdInsightsRoute
  '/op/clients/$clientId/invoices': typeof OpClientsClientIdInvoicesRoute
  '/op/clients/$clientId/settings': typeof OpClientsClientIdSettingsRoute
  '/w/$clientId/files/$requestId': typeof WClientIdFilesRequestIdRoute
  '/op/clients/$clientId/': typeof OpClientsClientIdIndexRoute
  '/w/$clientId/files/': typeof WClientIdFilesIndexRoute
  '/op/clients/$clientId/files/$requestId': typeof OpClientsClientIdFilesRequestIdRoute
  '/op/clients/$clientId/files/': typeof OpClientsClientIdFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/op'
    | '/signout'
    | '/unlinked'
    | '/w/$clientId'
    | '/op/invoices'
    | '/op/settings'
    | '/op/'
    | '/op/clients/$clientId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/w/$clientId/files'
    | '/w/$clientId/insights'
    | '/w/$clientId/invoices'
    | '/op/clients/'
    | '/w/$clientId/'
    | '/op/clients/$clientId/files'
    | '/op/clients/$clientId/insights'
    | '/op/clients/$clientId/invoices'
    | '/op/clients/$clientId/settings'
    | '/w/$clientId/files/$requestId'
    | '/op/clients/$clientId/'
    | '/w/$clientId/files/'
    | '/op/clients/$clientId/files/$requestId'
    | '/op/clients/$clientId/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signout'
    | '/unlinked'
    | '/op/invoices'
    | '/op/settings'
    | '/op'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/w/$clientId/insights'
    | '/w/$clientId/invoices'
    | '/op/clients'
    | '/w/$clientId'
    | '/op/clients/$clientId/insights'
    | '/op/clients/$clientId/invoices'
    | '/op/clients/$clientId/settings'
    | '/w/$clientId/files/$requestId'
    | '/op/clients/$clientId'
    | '/w/$clientId/files'
    | '/op/clients/$clientId/files/$requestId'
    | '/op/clients/$clientId/files'
  id:
    | '__root__'
    | '/'
    | '/op'
    | '/signout'
    | '/unlinked'
    | '/w/$clientId'
    | '/op/invoices'
    | '/op/settings'
    | '/op/'
    | '/op/clients/$clientId'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/w/$clientId/files'
    | '/w/$clientId/insights'
    | '/w/$clientId/invoices'
    | '/op/clients/'
    | '/w/$clientId/'
    | '/op/clients/$clientId/files'
    | '/op/clients/$clientId/insights'
    | '/op/clients/$clientId/invoices'
    | '/op/clients/$clientId/settings'
    | '/w/$clientId/files/$requestId'
    | '/op/clients/$clientId/'
    | '/w/$clientId/files/'
    | '/op/clients/$clientId/files/$requestId'
    | '/op/clients/$clientId/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpRouteRoute: typeof OpRouteRouteWithChildren
  SignoutRoute: typeof SignoutRoute
  UnlinkedRoute: typeof UnlinkedRoute
  WClientIdRouteRoute: typeof WClientIdRouteRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op': {
      id: '/op'
      path: '/op'
      fullPath: '/op'
      preLoaderRoute: typeof OpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlinked': {
      id: '/unlinked'
      path: '/unlinked'
      fullPath: '/unlinked'
      preLoaderRoute: typeof UnlinkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/': {
      id: '/op/'
      path: '/'
      fullPath: '/op/'
      preLoaderRoute: typeof OpIndexRouteImport
      parentRoute: typeof OpRouteRoute
    }
    '/op/invoices': {
      id: '/op/invoices'
      path: '/invoices'
      fullPath: '/op/invoices'
      preLoaderRoute: typeof OpInvoicesRouteImport
      parentRoute: typeof OpRouteRoute
    }
    '/op/settings': {
      id: '/op/settings'
      path: '/settings'
      fullPath: '/op/settings'
      preLoaderRoute: typeof OpSettingsRouteImport
      parentRoute: typeof OpRouteRoute
    }
    '/w/$clientId': {
      id: '/w/$clientId'
      path: '/w/$clientId'
      fullPath: '/w/$clientId'
      preLoaderRoute: typeof WClientIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/clients/': {
      id: '/op/clients/'
      path: '/clients'
      fullPath: '/op/clients/'
      preLoaderRoute: typeof OpClientsIndexRouteImport
      parentRoute: typeof OpRouteRoute
    }
    '/op/clients/$clientId': {
      id: '/op/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/op/clients/$clientId'
      preLoaderRoute: typeof OpClientsClientIdRouteRouteImport
      parentRoute: typeof OpRouteRoute
    }
    '/w/$clientId/': {
      id: '/w/$clientId/'
      path: '/'
      fullPath: '/w/$clientId/'
      preLoaderRoute: typeof WClientIdIndexRouteImport
      parentRoute: typeof WClientIdRouteRoute
    }
    '/w/$clientId/files': {
      id: '/w/$clientId/files'
      path: '/files'
      fullPath: '/w/$clientId/files'
      preLoaderRoute: typeof WClientIdFilesRouteImport
      parentRoute: typeof WClientIdRouteRoute
    }
    '/w/$clientId/insights': {
      id: '/w/$clientId/insights'
      path: '/insights'
      fullPath: '/w/$clientId/insights'
      preLoaderRoute: typeof WClientIdInsightsRouteImport
      parentRoute: typeof WClientIdRouteRoute
    }
    '/w/$clientId/invoices': {
      id: '/w/$clientId/invoices'
      path: '/invoices'
      fullPath: '/w/$clientId/invoices'
      preLoaderRoute: typeof WClientIdInvoicesRouteImport
      parentRoute: typeof WClientIdRouteRoute
    }
    '/op/clients/$clientId/': {
      id: '/op/clients/$clientId/'
      path: '/'
      fullPath: '/op/clients/$clientId/'
      preLoaderRoute: typeof OpClientsClientIdIndexRouteImport
      parentRoute: typeof OpClientsClientIdRouteRoute
    }
    '/op/clients/$clientId/files': {
      id: '/op/clients/$clientId/files'
      path: '/files'
      fullPath: '/op/clients/$clientId/files'
      preLoaderRoute: typeof OpClientsClientIdFilesRouteImport
      parentRoute: typeof OpClientsClientIdRouteRoute
    }
    '/op/clients/$clientId/insights': {
      id: '/op/clients/$clientId/insights'
      path: '/insights'
      fullPath: '/op/clients/$clientId/insights'
      preLoaderRoute: typeof OpClientsClientIdInsightsRouteImport
      parentRoute: typeof OpClientsClientIdRouteRoute
    }
    '/op/clients/$clientId/invoices': {
      id: '/op/clients/$clientId/invoices'
      path: '/invoices'
      fullPath: '/op/clients/$clientId/invoices'
      preLoaderRoute: typeof OpClientsClientIdInvoicesRouteImport
      parentRoute: typeof OpClientsClientIdRouteRoute
    }
    '/op/clients/$clientId/settings': {
      id: '/op/clients/$clientId/settings'
      path: '/settings'
      fullPath: '/op/clients/$clientId/settings'
      preLoaderRoute: typeof OpClientsClientIdSettingsRouteImport
      parentRoute: typeof OpClientsClientIdRouteRoute
    }
    '/w/$clientId/files/': {
      id: '/w/$clientId/files/'
      path: '/'
      fullPath: '/w/$clientId/files/'
      preLoaderRoute: typeof WClientIdFilesIndexRouteImport
      parentRoute: typeof WClientIdFilesRoute
    }
    '/w/$clientId/files/$requestId': {
      id: '/w/$clientId/files/$requestId'
      path: '/$requestId'
      fullPath: '/w/$clientId/files/$requestId'
      preLoaderRoute: typeof WClientIdFilesRequestIdRouteImport
      parentRoute: typeof WClientIdFilesRoute
    }
    '/op/clients/$clientId/files/': {
      id: '/op/clients/$clientId/files/'
      path: '/'
      fullPath: '/op/clients/$clientId/files/'
      preLoaderRoute: typeof OpClientsClientIdFilesIndexRouteImport
      parentRoute: typeof OpClientsClientIdFilesRoute
    }
    '/op/clients/$clientId/files/$requestId': {
      id: '/op/clients/$clientId/files/$requestId'
      path: '/$requestId'
      fullPath: '/op/clients/$clientId/files/$requestId'
      preLoaderRoute: typeof OpClientsClientIdFilesRequestIdRouteImport
      parentRoute: typeof OpClientsClientIdFilesRoute
    }
  }
}

interface OpClientsClientIdFilesRouteChildren {
  OpClientsClientIdFilesRequestIdRoute: typeof OpClientsClientIdFilesRequestIdRoute
  OpClientsClientIdFilesIndexRoute: typeof OpClientsClientIdFilesIndexRoute
}

const OpClientsClientIdFilesRouteChildren: OpClientsClientIdFilesRouteChildren =
  {
    OpClientsClientIdFilesRequestIdRoute: OpClientsClientIdFilesRequestIdRoute,
    OpClientsClientIdFilesIndexRoute: OpClientsClientIdFilesIndexRoute,
  }

const OpClientsClientIdFilesRouteWithChildren =
  OpClientsClientIdFilesRoute._addFileChildren(
    OpClientsClientIdFilesRouteChildren,
  )

interface OpClientsClientIdRouteRouteChildren {
  OpClientsClientIdFilesRoute: typeof OpClientsClientIdFilesRouteWithChildren
  OpClientsClientIdInsightsRoute: typeof OpClientsClientIdInsightsRoute
  OpClientsClientIdInvoicesRoute: typeof OpClientsClientIdInvoicesRoute
  OpClientsClientIdSettingsRoute: typeof OpClientsClientIdSettingsRoute
  OpClientsClientIdIndexRoute: typeof OpClientsClientIdIndexRoute
}

const OpClientsClientIdRouteRouteChildren: OpClientsClientIdRouteRouteChildren =
  {
    OpClientsClientIdFilesRoute: OpClientsClientIdFilesRouteWithChildren,
    OpClientsClientIdInsightsRoute: OpClientsClientIdInsightsRoute,
    OpClientsClientIdInvoicesRoute: OpClientsClientIdInvoicesRoute,
    OpClientsClientIdSettingsRoute: OpClientsClientIdSettingsRoute,
    OpClientsClientIdIndexRoute: OpClientsClientIdIndexRoute,
  }

const OpClientsClientIdRouteRouteWithChildren =
  OpClientsClientIdRouteRoute._addFileChildren(
    OpClientsClientIdRouteRouteChildren,
  )

interface OpRouteRouteChildren {
  OpInvoicesRoute: typeof OpInvoicesRoute
  OpSettingsRoute: typeof OpSettingsRoute
  OpIndexRoute: typeof OpIndexRoute
  OpClientsClientIdRouteRoute: typeof OpClientsClientIdRouteRouteWithChildren
  OpClientsIndexRoute: typeof OpClientsIndexRoute
}

const OpRouteRouteChildren: OpRouteRouteChildren = {
  OpInvoicesRoute: OpInvoicesRoute,
  OpSettingsRoute: OpSettingsRoute,
  OpIndexRoute: OpIndexRoute,
  OpClientsClientIdRouteRoute: OpClientsClientIdRouteRouteWithChildren,
  OpClientsIndexRoute: OpClientsIndexRoute,
}

const OpRouteRouteWithChildren =
  OpRouteRoute._addFileChildren(OpRouteRouteChildren)

interface WClientIdFilesRouteChildren {
  WClientIdFilesRequestIdRoute: typeof WClientIdFilesRequestIdRoute
  WClientIdFilesIndexRoute: typeof WClientIdFilesIndexRoute
}

const WClientIdFilesRouteChildren: WClientIdFilesRouteChildren = {
  WClientIdFilesRequestIdRoute: WClientIdFilesRequestIdRoute,
  WClientIdFilesIndexRoute: WClientIdFilesIndexRoute,
}

const WClientIdFilesRouteWithChildren = WClientIdFilesRoute._addFileChildren(
  WClientIdFilesRouteChildren,
)

interface WClientIdRouteRouteChildren {
  WClientIdFilesRoute: typeof WClientIdFilesRouteWithChildren
  WClientIdInsightsRoute: typeof WClientIdInsightsRoute
  WClientIdInvoicesRoute: typeof WClientIdInvoicesRoute
  WClientIdIndexRoute: typeof WClientIdIndexRoute
}

const WClientIdRouteRouteChildren: WClientIdRouteRouteChildren = {
  WClientIdFilesRoute: WClientIdFilesRouteWithChildren,
  WClientIdInsightsRoute: WClientIdInsightsRoute,
  WClientIdInvoicesRoute: WClientIdInvoicesRoute,
  WClientIdIndexRoute: WClientIdIndexRoute,
}

const WClientIdRouteRouteWithChildren = WClientIdRouteRoute._addFileChildren(
  WClientIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpRouteRoute: OpRouteRouteWithChildren,
  SignoutRoute: SignoutRoute,
  UnlinkedRoute: UnlinkedRoute,
  WClientIdRouteRoute: WClientIdRouteRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
